sphereface:
	s: 9  # paper default: 30
	m: 1.5  # paper default: 1.5

cosface:
	s: 9  # paper default: 64
	m: 0.35  # paper default: 0.35

arcface:
	s: 9  # paper default: 64
	m: 0.5  # paper default: 0.5

magface:
	s: 9
	l_a: 10  # paper default: 10  (lower bound on feature magnitude)
	u_a: 110  # paper default: 110 (upper bound on feature magnitude)
	l_m: 0.4  # paper default: 0.4 (lower bound on angle)
	u_m: 0.8 . # paper default: 0.8 (upper bound on angle)
	lambda_g: 4  # paper default: 35

cosos:
	s: None
	m: 0.35
	xi: 9
	lambda_os: 0.01
	variable_magnitude_during_testing: True

arcos:
	s: None
	xi: 9
	lambda_os: 0.01
	variable_magnitude_during_testing: True
