# ===== benchmarks =====
objectosphere:
  lambda: 0.01  # paper default on toy data: 0.0001
  xi: 13  # paper default on toy data: 50
  symmetric: False


# ===== face losses (HFN) =====
sphereface:
  s: 13  # paper default: 30
  m: 1.2  # paper default: 1.2, code default: 1.5

cosface:
  s: 13  # paper default: 64
  m: 0.35  # paper default: 0.35; see paper suplement for upper bound

arcface:
  s: 13  # paper default: 64
  m: 0.5  # paper default: 0.5, 0.2 worked well on p0 with 2-dim deep features

sm_softmax:
  s: null
  m: 0.3
  w_normalization: False


# ===== face losses (SFN) ===== (use ring loss)
norm_sfn:
  s: null  # null gets convertet to None
  m: 0  # 0
  lambda: 0.01
  xi: 13

cosface_sfn:
  s: null  # null gets convertet to None
  m: 0.35  # 0.35
  lambda: 0.01
  xi: 13

arcface_sfn:
  s: null  # null gets convertet to None
  m: 0.5  # 0.5
  lambda: 0.01
  xi: 13

  
# ===== margin-OS (SFN) =====
softmax_os:
  s: null  # null gets convertet to None
  m: 0  # 0
  w_normalization: True  # set False for no normalization
  lambda: 0.01
  xi: 13
  symmetric: True  # symmetric penalty on deviation xi-||F(x)|| of knowns

cos_os:
  s: null  # null gets convertet to None
  m: 0.35  # 0.35
  lambda: 0.01
  xi: 13
  symmetric: True  # symmetric penalty on deviation xi-||F(x)|| of knowns

arc_os:
  s: null  # null gets convertet to None
  m: 0.5  # 0.5
  lambda: 0.01
  xi: 13
  symmetric: True  # symmetric penalty on deviation xi-||F(x)|| of knowns

cos_os_non_symmetric:
  s: null  # null gets convertet to None
  m: 0.35  # 0.35
  lambda: 0.01
  xi: 13
  symmetric: False  # symmetric penalty on deviation xi-||F(x)|| of knowns

arc_os_non_symmetric:
  s: null  # null gets convertet to None
  m: 0.5  # 0.5
  lambda: 0.01
  xi: 13
  symmetric: False  # symmetric penalty on deviation xi-||F(x)|| of knowns


# ===== margin-EOS (HFN) =====
norm_eos:
  s: 13  # null gets convertet to None
  m: 0  # 0
  w_normalization: True  # set False for no normalization

cos_eos:
  s: 13  # null gets convertet to None
  m: 0.35  # 0.35
  
arc_eos:
  s: 13  # null gets convertet to None
  m: 0.5  # 0.5


# ===== margin-EOS (SFN) =====
cos_eos_sfn:
  s: 13  # null gets convertet to None
  m: 0.35  # 0.35
  lambda: 0.01
  xi: 13
  
arc_eos_sfn:
  s: 13  # null gets convertet to None
  m: 0.5  # 0.5
  lambda: 0.01
  xi: 13